### ISSUE TITLE
Caching Everything

### ISSUE THREAD

**Issue by lukaskollmer** [TCA-Team/iOS#156]
If individual room maps images aren't too large, we should consider caching them on device.

Obvious advantage of this is performance: if we don't have to load the images from the internet, we can display them way faster if the user is on a slow connection.

**Comment by kordianbruck** [comment]
How do you want to add the marker for the maps? Locally on the phone?

**Comment by mathiasquintero** [comment]
I'd actually suggest that we start thinking of a general caching and refreshing behavior. We should cache everything and in every screen allow users to force a refresh.

Maybe even allow them to set the caching times for each feature in settings

**Comment by TG908** [comment]
@mathiasquintero the refresh could be done with a simple pull to refresh

**Comment by mathiasquintero** [comment]
@TG908 Intuitively. Yes. That's exactly what pull to refresh means. 
I just don't know if it's the best idea...
@kordianbruck what do you think? If the user does a pull to refresh in the cards view, should the cards be loaded from scratch?

**Comment by kordianbruck** [comment]
Well no, you shouldn't necessarily clear all caches. Stuff like the mensa will almost never change in my experience. You can clear some of the caches like the fees or something. I'm not sure we delete any caches on Pull to Refresh in Android.

**Comment by mathiasquintero** [comment]
Ok. But if we were to refresh everything that is in the cards view, it wouldn't be a big deal, right?

**Comment by mathiasquintero** [comment]
@kordianbruck for testing I have this behavior in my branch. If you want to test it out. Any fetching of the cards that isn't triggered by a pull to refresh checks the cache. Only pull to refresh skips the cache

**Comment by kordianbruck** [comment]
@pfent what do you think? Smart move? Maybe we should also do this in the android version?

**Comment by pfent** [comment]
@kordianbruck I don't think this is a smart move.

IMHO the application should honor the [HTTP Cache-Control headers](https://developer.mozilla.org/de/docs/Web/HTTP/Headers/Cache-Control), but I think all the *tum.de sites don't set them.

So on pull-to-refresh, we should probably only do [HTTP HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) requests and check, if the caches are outdated. I.e. check the Date field in the header:
```bash
curl -Is https://portal.mytum.de/campus/roomfinder/getRoomMap\?mapid\=142\&roomid\=00.01.001@5601 | grep Date
```

We could also try to do [conditional GETs with the If-Modified-Since header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since), but I don't know if any of the TUM servers honor that header

In the Android version, we could only ponder ditching our own years-old, hand-rolled CacheManager and [do it the right way](https://github.com/square/okhttp/wiki/Recipes#response-caching)

**Comment by mathiasquintero** [comment]
@pfent but the endpoints that really matter always set the current date as the date in HEAD requests. If we want to do that then TUMOnline will have to adhere to it as well...
