### ISSUE TITLE
Use new icons

### ISSUE THREAD

**Issue by kordianbruck** [TCA-Team/iOS#236]
[iOS Export.zip](https://github.com/TCA-Team/iOS/files/1718228/iOS.Export.zip)

**Comment by lukaskollmer** [comment]
What about a white background w/ a blue logo?

**Comment by mathiasquintero** [comment]
@lukaskollmer For the icon you mean?

**Comment by lukaskollmer** [comment]
yes. maybe something like [this](https://files.lukaskollmer.me/embed/tca/tca_logo.png)?

i made the tum logo a bit larger since (imo) it's way too small in the current app icon

anyway, here are the resources, in case you want to make some changes:
- [tca_logo.pxm](https://files.lukaskollmer.me/embed/tca/tca_logo.pxm)
- [tca_logo.appiconset](https://files.lukaskollmer.me/embed/tca/tca_logo.appiconset.zip)

**Comment by kordianbruck** [comment]
@lukaskollmer the current icons above we got from the offical designer for the TUM CI. So I'd rather not do a custom variant - it needs to work for both Android and iOS.

**Comment by jpbernius** [comment]
What about supporting blue on white as an alternate icon?
[`setAlternateIconName(_:completionHandler:)`](https://developer.apple.com/documentation/uikit/uiapplication/2806818-setalternateiconname)
