### ISSUE TITLE
Feature Proposal: New Card for Newest Grades

### ISSUE THREAD

**Issue by melloskitten** [TCA-Team/iOS#68]
How about a card that shows your newest Grade? I think it would be quite handy to just take a look at your TUM app and see your newest grade when you receive the email, instead of checking out the website - Or you can see all your grades at once for the semester you're in or something.

**Comment by mammuth** [comment]
Nice idea. 

This could be thought even further. We could have a background fetch which checks for new grades. Since this background operation is not needed most of the time, this check should only run during the couple of weeks (/months?) where exam grades are published most of the time. 

It could be even smarter and disable the background fetch earlier when there are grades for all lectures/exams that the user was registered to.

If that's something worth thinking about we should open an own issue for it.

**Comment by kordianbruck** [comment]
One more thing: please do not save the grades on the phone. You can save an ID or something (no hash), but this is too critical to have stored somewhere. (Unless we start encrypting)

**Comment by melloskitten** [comment]
Thank you. I'll see what I can come up with -!

**Comment by TG908** [comment]
Implemented in #251
