### ISSUE TITLE
Study room Notifications

### ISSUE THREAD

**Issue by TG908** [TCA-Team/iOS#96]
The user should be notified on demand with a push notifcation when a study room becomes available.

**Comment by kordianbruck** [comment]
Okay, this needs to be more specific (For a specific room or in general? What if the room gets booked again within 5 minutes?). Also technically this is sketchy as there are little possibilities on how to run background services on iOS. Also why is this high priority? Please elaborate...

**Comment by TG908** [comment]
They can set the nofitication for all the rooms or for single specific rooms. We can run our own server sensing or the push notifications

**Comment by TG908** [comment]
The device then registers on our backend for notifications for all rooms or room x

**Comment by mammuth** [comment]
What do you think when a user requests push notifications? Do you expect them to unregister again? Should notifications for all rooms be triggered when an occupied room becomes free or only if there is no free room and then an occupied room becomes free? Are notifications only send when the user is near the room (and not at eg home)? 

I guess there are even more open UX questions. 

When I search for a room in the MI, I fire up the app, look whether there is an free room, go to it. If none is free I search for alternatives like just sitting in the Magistrale or check out some rooms that are not yet listed in the study rooms tool. 
I don't really know how I could benefit from setting alerts when a room gets free in this scenario. Because I'm looking for a room "now" and not "sometime in the future".

**Comment by TG908** [comment]
If you're sitting in the magistrate you might still want to change to a study room if one becomes available. The user will only be notified once and can choose to get notifications for every room or a few selected rooms.

**Comment by mammuth** [comment]
Seems legit. It also makes sense to unsubscribe automatically after one notification. Cool!

**Comment by TG908** [comment]
Any special requirements for the backend. I'd go for swift (vapor) or go

**Comment by mammuth** [comment]
The current backend is already using GCM to send push notifications to android and it's planned to use the same backend to send notifications to the iOS app as well. 
Other feature that will be based on the current backend (and need push notifications) are eg. the alarm service (#9) or the chat (#16). 

We can discuss / implement this tomorrow when we meet (together with @kordianbruck since we probably need changes at the backend)! 😊 

Furthermore, this is a feature we should probably also support on Android, so I guess it makes sense to open an issue there as well just to keep track of it.

**Comment by TG908** [comment]
not realisable
